export const COMETCHAT_CONSTANTS = {
  NO_ITEM_SELECTED_MESSAGE: "Select a chat to start messaging",
  LOADING_MESSSAGE: "Loading...",
  ADDING_MESSSAGE: "Adding...",
  CREATING_MESSSAGE: "Creating...",
  SEARCH_LOADING: "Searching...",
  ERROR_LOADING_USERS: "Error in loading users",
  ERROR_LOADING_CHATS: "Error in loading chats",
  ERROR_COMETCHAT_LOGIN: "Log in error, reload",
  ERROR_NO_USERS_FOUND: "No users found",
  EMPTY_STRING: "",
  SINGLE_SPACE: " ",
  USERS: "Danh bạ",
  LIST_ADD_FRIEND: "Danh sách kết bạn",
  CHATS: "Tin nhắn",
  GROUPS: "Tin nhắn nhóm",
  MORE: "Tùy chọn",
  MESSAGE_IMAGE: "📷 Image",
  MESSAGE_FILE: "📁 File",
  MESSAGE_VIDEO: "🎥 Video",
  MESSAGE_AUDIO: "🎵 Audio",
  CUSTOM_MESSAGE: "You have a message",
  MISSED_VOICE_CALL: "Missed voice call",
  MISSED_VIDEO_CALL: "Missed video call",
  CALL_UNANSWERED: "Call unanswered",
  MISSED_AUDIO_CALL: "Missed audio call",
  CUSTOM_MESSAGE_POLL: "📊 Poll",
  CUSTOM_MESSAGE_STICKER: "💟 Sticker",
  CUSTOM_MESSAGE_DOCUMENT: "📃 Document",
  CUSTOM_MESSAGE_WHITEBOARD: "📝 Whiteboard",
  ONLINE: "Online",
  ADMINISTRATOR: "Administrator",
  MODERATOR: "Moderator",
  PARTICIPANT: "Participant",
  PUBLIC: "Public",
  PRIVATE: "Private",
  PASSWORD_PROTECTED: "Password Protected",
  PRIVACY_AND_SECURITY: "Privacy and Security",
  PREFERENCES: "Preferences",
  MEMBERS: "Các thành viên",
  TODAY: "Hôm nay",
  YESTERDAY: "Hôm qua",
  TYPING: "typing...",
  IS_TYPING: "is typing...",
  CLOSE: "Close",
  ENTER_GROUP_NAME: "Nhập tên nhóm",
  ADD_MEMBERS: "Thêm thành viên",
  SEND_MESSAGE: "Send Message",
  UNBLOCK_USER: "Mở khoá người dùng",
  BLOCK_USER: "Chặn người dùng",
  DELETE_AND_EXIT: "Delete and Exit",
  LEAVE_GROUP: "Rời khỏi nhóm",
  SHARED_MEDIA: "Shared Media",
  VIDEO_CALL: "Video call",
  AUDIO_CALL: "Audio call",
  REPLY: "reply",
  REPLIES: "replies",
  LAUNCH: "Launch",
  SHARED_COLLABORATIVE_DOCUMENT: "has shared a collaborative document",
  SHARED_COLLABORATIVE_WHITEBOARD: "has shared a collaborative whiteboard",
  CREATED_WHITEBOARD: "You’ve created a new collaborative whiteboard",
  CREATED_DOCUMENT: "You’ve created a new collaborative document",
  PHOTOS: "Photos",
  VIDEOS: "Videos",
  DOCUMENT: "Document",
  YOU_DELETED_THIS_MESSAGE: "Bạn đã xóa tin nhắn này",
  THIS_MESSAGE_DELETED: "Tin nhắn này đã bị xóa",
  VIEW_ON_YOUTUBE: "View on Youtube",
  SEARCH: "Tìm kiếm",
  NO_USERS_FOUND: "Không tìm thấy",
  ERROR: "Error",
  NO_GROUPS_FOUND: "Không tìm thấy nhóm nào",
  NO_CHATS_FOUND: "No chats found",
  MEDIA_MESSAGE: "Media message",
  INCOMING_AUDIO_CALL: "Incoming audio call",
  INCOMING_VIDEO_CALL: "Incoming video call",
  DECLINE: "Decline",
  ACCEPT: "Accept",
  CALL_INITIATED: "Call initiated",
  OUTGOING_AUDIO_CALL: "Outgoing audio call",
  OUTGOING_VIDEO_CALL: "Outgoing video call",
  CALL_REJECTED: "Call rejected",
  REJECTED_CALL: "rejected call",
  CALL_ACCEPTED: "Call accepted",
  JOINED: "joined",
  LEFT_THE_CALL: "left the call",
  UNANSWERED_AUDIO_CALL: "Unanswered audio call",
  UNANSWERED_VIDEO_CALL: "Unanswered video call",
  CALL_ENDED: "Call ended",
  CALL_CANCELLED: "Call cancelled",
  CALL_BUSY: "Call busy",
  CALLING: "Calling...",
  ADD: "Add",
  NO_BANNED_MEMBERS_FOUND: "No banned members found",
  BANNED_MEMBERS: "Banned Members",
  NAME: "Tên",
  SCOPE: "Phân Quyền",
  UNBAN: "Unban",
  SELECT_GROUP_TYPE: "Select group type",
  ENTER_GROUP_PASSWORD: "Enter group password",
  CREATE: "Tạo",
  ADD_FRIEND: "Kết bạn",
  UPDATE: "Cập nhật",
  CREATE_GROUP: "Tạo nhóm",
  ADD_FRIENDS: "Nhập số điện thoại để kết bạn",
  CREATE_POLL: "Create Poll",
  QUESTION: "Question",
  ENTER_YOUR_QUESTION: "Enter your question",
  OPTIONS: "Lựa chọn khác",
  ENTER_YOUR_OPTION: "Enter your option",
  ADD_NEW_OPTION: "Add new option",
  VIEW_MEMBERS: "Xem thành viên",
  DETAILS: "THÔNG TIN CHI TIẾT",
  NOTIFICATIONS: "Notifications",
  OTHER: "Other",
  HELP: "Help",
  REPORT_PROBLEM: "Report a Problem",
  GROUP_MEMBERS: "Thành viên nhóm",
  BAN: "Ban",
  KICK: "Kick",
  PICK_YOUR_EMOJI: "Pick your emoji",
  PRIVATE_GROUP: "Private Group",
  PROTECTED_GROUP: "Protected Group",
  VISIT: "Visit",
  ATTACH: "Attach",
  ATTACH_FILE: "Gửi file",
  ATTACH_VIDEO: "Gửi video",
  ATTACH_AUDIO: "Attach audio",
  ATTACH_IMAGE: "Gửi hình ảnh",
 
  //
  COLLABORATE_USING_DOCUMENT: "Collaborate using a document",
  COLLABORATE_USING_WHITEBOARD: "Collaborate using a whiteboard",
  ADD_EMOJI: "Biểu cảm",
  EMOJI: "Emoji",
  ENTER_YOUR_MESSAGE_HERE: "Nhập tin nhắn của bạn ở đây",
  NO_MESSAGES_FOUND: "Không tìm thấy tin nhắn nào",
  THREAD: "Thread",
  COLLABORATIVE_DOCUMENT: "Collaborative Document",
  COLLABORATIVE_WHITEBOARD: "Collaborative Whiteboard",
  ADD_REACTION: "Add reaction",
  HEART: "heart",
  NO_STICKERS_FOUND: "No stickers found",
  REPLY_TO_THREAD: "Reply to thread",
  REPLY_IN_THREAD: "Reply in thread",
  DELETE_MESSAGE: "Delete message",
  EDIT_MESSAGE: "Edit message",
  SUNDAY: "SUNDAY",
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  GROUP_NAME_BLANK: "Group name cannot be blank",
  GROUP_TYPE_BLANK: "Group type cannot be blank",
  GROUP_PASSWORD_BLANK: "Group password cannot be blank",
  POLL_QUESTION_BLANK: "Question cannot be blank",
  POLL_OPTION_BLANK: "Option cannot be blank",
  OWNER: "owner",
  CALLS: "Calls",
  CUSTOM_MESSAGE_LOCATION: "📍Location",
  YOU: "Bạn",
  PRIVACY: "Privacy",
  BLOCKED_USERS: "Blocked Users",
  "YOU'VE_BLOCKED": "You've blocked",
  NO_PHOTOS: "No Photos",
  NO_VIDEOS: "No Videos",
  NO_DOCUMENTS: "No Documents",
  NO_RECORDS_FOUND: "No records found.",
  JOIN: "Join",
  SENT: "sent",
  DELIVERED: "deliv",
  ENTER_YOUR_PASSWORD: "Enter your password",
  LAST_ACTIVE_AT: "Last Active At: ",
  REACTED: "reacted",
  //mycode
  PERSON_INFO : "Thông tin cá nhân",
  LOGOUT : "Đăng xuất",
  LIST_ADD_FRIEND_ : "Đăng xuất",
  DELETE_FRIEND : "Xóa bạn bè",
};
